// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYasObEwakbokw1bihz8OlNUHhLE0pFLk',
    appId: '1:428182730427:web:c5ce900885600572a45b9e',
    messagingSenderId: '428182730427',
    projectId: 'instagram-clone-c1600',
    authDomain: 'instagram-clone-c1600.firebaseapp.com',
    storageBucket: 'instagram-clone-c1600.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm5H8yrBujnT9Lf0uq8VbYygfMo69cedg',
    appId: '1:428182730427:android:aaa01adf64f88bbfa45b9e',
    messagingSenderId: '428182730427',
    projectId: 'instagram-clone-c1600',
    storageBucket: 'instagram-clone-c1600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy17C5RtVqfv1syGakKvD31kTr500Ycn0',
    appId: '1:428182730427:ios:f366eb08a39fdceca45b9e',
    messagingSenderId: '428182730427',
    projectId: 'instagram-clone-c1600',
    storageBucket: 'instagram-clone-c1600.appspot.com',
    iosClientId: '428182730427-0e3v874pfi8jj8utvhkhmjamuh9bsps3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy17C5RtVqfv1syGakKvD31kTr500Ycn0',
    appId: '1:428182730427:ios:f366eb08a39fdceca45b9e',
    messagingSenderId: '428182730427',
    projectId: 'instagram-clone-c1600',
    storageBucket: 'instagram-clone-c1600.appspot.com',
    iosClientId: '428182730427-0e3v874pfi8jj8utvhkhmjamuh9bsps3.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
